version: '3'

services:
  fluentd-elasticsearch:
    image: fluentd-es:latest
    volumes:
      - ./etc:/fluentd/etc
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    ports:
      - "24224:24224"
    environment:
      - FLUENTD_CONF=fluentd.conf
