version: '2'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        container_name: es-4854
        command: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
          - discovery.type=single-node
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - ./data:/usr/share/elasticsearch/data
        networks:
          - elastic


    kibana:
         image: kibana:7.6.1
         hostname: kibana
         ports:
            - "5601:5601"
         environment:
            ELASTICSEARCH_URL: "http://localhost:9200"
            xpack.security.enabled: "false"
         depends_on:
            - elasticsearch
         networks:
            - elastic


networks:
  elastic:
    driver: bridge
