version: '3.2'

services:
    aerospikedb:
        image: aerospike/aerospike-server:4.3.1.4 
        networks:
        - aerospikenetwork
        deploy:
            mode: global
         #   replicas: 6
        labels:
            com.aerospike.description: "This label is for all containers for the Aerospike service"
        command: [ "--config-file","/run/secrets/aerospike.conf"]
        secrets:
        - source: conffile
          target: aerospike.conf
          mode: 0440
    

networks:
    aerospikenetwork:
        external:
            name: "host"

secrets:
    conffile:
        file: ./aerospike.conf
